module.exports = {
    dsa: [
        // "DFSOnBST",
        // "LRU",
        "LinearSearchList",
        "BinarySearchList",
        // "TwoCrystalBalls",
        "BubbleSort",
        "ArrayList",
        // "MazeSolver",
        "QuickSort",
        // "BTPreOrder",
        // "BTInOrder",
        // "BTPostOrder",
        // "BTBFS",
        // "CompareBinaryTrees",
        // "DFSOnBST",
        // "DFSGraphList",
        // "Trie",
        // "BFSGraphMatrix",
        // "Map",
        // "MinHeap",
    ],
}

